name: notifier
version: 0.1.2
description: A web app that uses AngularDart Components
homepage: https://github.com/Augustpi/notifier
author: Avni Onur Pehlivan <avnionur@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: 2.1.0
  test: 1.6.4
